/* 30-second local observation desk. Untrusted reports are text, never executable HTML. */
(() => {
 'use strict';
 const root=document.querySelector('.app'); if(!root)return;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=String(text);if(cls)n.className=cls;return n;};
 const style=el('style');style.textContent=`
 .fd{color:#192a41}.fd-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin:14px 0}.fd h2{font-size:21px;margin:0;letter-spacing:-.5px}.fd-sub{color:#62728a;font-size:11px;line-height:1.65}.fd-status{font-size:11px;color:#53657e}.fd-controls{display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin:12px 0}.fd-btn,.fd input,.fd select{border:1px solid #d0dcef;background:#fff;color:#284873;border-radius:8px;padding:7px 10px;font:inherit}.fd-btn{cursor:pointer}.fd-btn[aria-pressed=true]{background:#273990;color:white;border-color:#273990}.fd-btn:focus-visible,.fd input:focus-visible{outline:3px solid #b6cbfd}.fd input{min-width:170px;max-width:100%}
 .fd-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.fd-kpi{padding:12px 14px;border:1px solid #d6e2f1;border-radius:11px;background:#fff;border-left:4px solid #5a65d8}.fd-kpi:nth-child(2){border-left-color:#e38a36}.fd-kpi:nth-child(3){border-left-color:#16a397}.fd-kpi:nth-child(4){border-left-color:#8b68c5}.fd-kpi strong{display:block;font-size:20px;line-height:1.5}.fd-badge{display:inline-block;padding:3px 6px;border-radius:6px;background:#eef1f7;font-size:10px;color:#52657e;line-height:1.5}.fd-teal{background:#ddf5ef;color:#117059}.fd-amber{background:#fff1dc;color:#8b5b16}.fd-red{background:#ffeded;color:#ad3c42}.fd-purple{background:#eeeaff;color:#5948a0}
 .fd-groups{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.fd-group{background:#fff;border:1px solid #d4e1ef;border-top:4px solid #665dc6;border-radius:11px;overflow:hidden}.fd-group:nth-child(3n+2){border-top-color:#18a08b}.fd-group:nth-child(3n){border-top-color:#dba239}.fd-ghead{padding:11px 12px 8px}.fd-ghead h3{margin:0;font-size:13px;line-height:1.5}.fd-gmetrics{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding-top:8px}.fd-gmetrics strong{font-size:18px}.fd-share{height:5px;background:#edf1f8;margin:8px 0}.fd-share span{height:100%;display:block;background:linear-gradient(90deg,#6674dc,#39b6b4)}.fd-peer{display:grid;grid-template-columns:minmax(0,1fr) 75px 75px;gap:6px;padding:8px 12px;border-top:1px solid #edf2f8;font-size:11px;align-items:center}.fd-peer button{border:0;background:none;padding:0;text-align:left;font-weight:700;color:#283e62;cursor:pointer}.fd-peer span{text-align:right}.fd-up{color:#cd424b}.fd-down{color:#3f69bd}
 .fd-body{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(330px,1fr);gap:12px;margin-top:14px;align-items:start}.fd-sheet,.fd-detail{background:#fff;border:1px solid #d4e1ef;border-radius:12px;overflow:hidden}.fd-detail{padding:15px;position:sticky;top:60px}.fd-detail h3{margin:0 0 4px;font-size:20px}.fd-detail h4{font-size:12px;margin:14px 0 6px;color:#3c4c75}.fd-detail p{margin:5px 0;font-size:12px;line-height:1.8}.fd-report{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;line-height:1.85}.fd-report a,.fd-links a{color:#375bb0;text-decoration:underline}.fd-links{font-size:11px;padding:10px 0}.fd-scroll{overflow:auto;max-height:780px}.fd-table{width:100%;border-collapse:collapse;font-size:11px;min-width:980px}.fd-table th{position:sticky;top:0;background:#f3f7fc;color:#63748c;font-size:10px;padding:10px 8px;text-align:right;z-index:1}.fd-table td{padding:9px 8px;border-top:1px solid #eef2f8;text-align:right;white-space:nowrap}.fd-table td:first-child,.fd-table th:first-child{text-align:left}.fd-table tr[data-selected=true]{background:#edf4ff}.fd-name{font-weight:800;color:#243a64;border:0;background:none;cursor:pointer;padding:0}.fd-table .fd-small{font-size:9px;color:#7c8798}.fd-spark{width:75px;height:26px;display:block}.fd-note{background:#edf2fa;border-radius:9px;padding:10px 12px;font-size:11px;color:#526681;line-height:1.7;margin-top:10px}.fd-title{font-size:14px;font-weight:800;margin:16px 0 8px}.fd-progress{font-size:11px;color:#6c56a9}.fd-empty{padding:16px;font-size:12px;line-height:1.8;color:#62738a}.fd-chartbox{margin-top:10px}.fd-rotation{background:#fff;border:1px solid #d4e1ef;border-radius:12px;padding:12px;margin:10px 0}.fd-rotation-head{display:flex;justify-content:space-between;gap:8px;align-items:end;margin-bottom:7px}.fd-rotation-row{display:grid;grid-template-columns:minmax(140px,1fr) 88px 86px 105px;gap:7px;align-items:center;padding:7px 0;border-top:1px solid #edf2f8}.fd-rotation-row:first-of-type{border-top:0}.fd-rotation-row strong{font-size:11px}.fd-rotation-row .fd-spark{width:100px}.fd-rotation-row span{text-align:right;font-size:10px}.fd-chartbox svg{width:100%;display:block}.fd-chartmeta{display:flex;justify-content:space-between;gap:8px;font-size:10px;color:#62748d;margin:4px 0}.fd-chartdialog{width:min(1020px,96vw);border:1px solid #c9d6ea;border-radius:14px;padding:18px;max-height:94vh;overflow:auto;background:#fff;color:#192a41}.fd-chartdialog::backdrop{background:#192a417a}.fd-chartdialog h3{margin:0}.fd-chartdialog .fd-btn{margin:3px}.fd-details-inline{padding:3px 0}.fd-links details{margin:5px 0}.fd-legend{display:flex;gap:10px;font-size:10px;color:#657389}
 @media(max-width:1180px){.fd-groups{grid-template-columns:repeat(2,minmax(0,1fr))}.fd-body{grid-template-columns:1fr}.fd-detail{position:static}.fd-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.fd-head{align-items:start;flex-direction:column}.fd h2{font-size:18px}.fd-groups{grid-template-columns:1fr}.fd-rotation-row{grid-template-columns:minmax(120px,1fr) 70px 78px}.fd-rotation-row .fd-spark{grid-column:1/-1;width:100%;height:30px}.fd-kpi{padding:8px 10px}.fd-kpi strong{font-size:17px}.fd-body{display:block}.fd-detail{margin-top:12px}.fd-chartdialog{padding:10px}.fd-peer{grid-template-columns:minmax(0,1fr) 75px 80px}}
 `;document.head.append(style);
 const view=el('section',null,'view fd');view.id='view-flow';root.append(view);
 function switchView(){if(typeof window.setView==='function')window.setView('flow');else{document.querySelectorAll('.view').forEach(n=>n.classList.toggle('active',n===view));document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view==='flow'));}load(true);}
 for(const id of ['tabs','bottom']){const nav=document.getElementById(id);if(!nav)continue;const b=el('button',id==='bottom'?'30초 흐름':'30초 흐름',id==='tabs'?'tab':'');b.dataset.view='flow';b.addEventListener('click',switchView);nav.insertBefore(b,nav.children[1]||null);}
 const header=el('div',null,'fd-head'),title=el('div');title.append(el('h2','재료별 거래 집중도 · 30초'),el('div','무엇이 거래되고, 얼마나 빨라졌는가. 순매수 자금이 아닌 거래대금의 변화입니다.','fd-sub'));
 const refresh=el('button','새로고침','fd-btn');header.append(title,refresh);
 const state=el('div','관측 자료 확인 중','fd-status'),kpis=el('div',null,'fd-kpis'),controls=el('div',null,'fd-controls');
 const byEvent=el('button','재료 × 시장테마','fd-btn'),byTheme=el('button','시장테마','fd-btn'),bySector=el('button','사업 세부업종','fd-btn'),search=el('input');search.type='search';search.placeholder='종목·코드·업종 검색';search.setAttribute('aria-label','흐름 검색');
 const sort=el('select');[['delta','최근 대금순'],['burst','거래 속도순'],['total','누적 대금순'],['query','조회 순위순']].forEach(([v,t])=>{const o=el('option',t);o.value=v;sort.append(o);});sort.setAttribute('aria-label','종목 정렬');
 controls.append(byEvent,byTheme,bySector,search,sort);byEvent.setAttribute('aria-pressed','true');byTheme.setAttribute('aria-pressed','false');bySector.setAttribute('aria-pressed','false');
 const rotationBox=el('section',null,'fd-rotation'),groupbox=el('div',null,'fd-groups'),groupnote=el('div',null,'fd-note');
 const body=el('div',null,'fd-body'),sheet=el('div',null,'fd-sheet'),scroll=el('div',null,'fd-scroll'),table=el('table',null,'fd-table'),thead=el('thead'),thr=el('tr'),tbody=el('tbody');
 ['종목 · 세부업종','등락','누적 거래대금','최근 구간 대금','최근 5분','속도 배율','시총 / 대금비','주가 추이'].forEach(s=>thr.append(el('th',s)));thead.append(thr);table.append(thead,tbody);scroll.append(table);sheet.append(scroll);
 const detail=el('aside',null,'fd-detail');body.append(sheet,detail);
 view.append(header,state,kpis,controls,rotationBox,groupbox,groupnote,el('div','종목별 거래 폭발 · 재료 종합','fd-title'),body);
 const dialog=el('dialog',null,'fd-chartdialog fd');dialog.setAttribute('aria-label','종목 차트');document.body.append(dialog);
 let DATA=null,mode='catalyst',selected=null,focusCode=null,chartFrame='minute',chartInfo=null,busy=false,lastLoaded=0,groupFilter=null,chartVersion=0;
 const fmt=(n,d=1)=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:d});
 const money=n=>n==null?'—':Math.abs(n)>=1e8?fmt(n/1e8,2)+'억':Math.abs(n)>=1e6?fmt(n/1e6,2)+'백만':fmt(n,0)+'원';
 const stamp=t=>t?new Date(t).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'미확인';
 const rate=n=>n==null?'—':(n>0?'+':'')+fmt(n,2)+'%';const sign=n=>n>0?'fd-up':n<0?'fd-down':'';
 const rowOf=c=>(DATA?.rows||[]).find(r=>r.code===c);
 function button(text,fn){const b=el('button',text,'fd-btn');b.addEventListener('click',fn);return b;}
 function badge(s,cls=''){return el('span',s,'fd-badge '+cls);}
 function accessKey(){try{return localStorage.getItem('marketRadarToken')||'';}catch(_){return '';}}
 async function get(url,options={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),18000);try{const r=await fetch(url,{...options,headers:{'x-dashboard-token':accessKey(),...(options.headers||{})},cache:'no-store',signal:ctl.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(timer);}}
 function link(url,text){try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw 0;const a=el('a',text);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}catch(_){return el('span',text);}}
 function annotation(report){const box=el('div',null,'fd-report'),chars=Array.from(report?.text||'');let p=0,n=0;for(const a of [...(report?.citations||[])].sort((x,y)=>x.start-y.start)){if(!Number.isInteger(a.start)||a.start<p||a.end>chars.length||a.end<=a.start)continue;box.append(document.createTextNode(chars.slice(p,a.start).join('')),link(a.url,'[출처 '+(++n)+']'));p=a.end;}box.append(document.createTextNode(chars.slice(p).join('')));return box;}
 const svg=(tag,attrs={})=>{const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;};
 function spark(points){const values=(points||[]).map(p=>p.value).filter(x=>x!=null&&Number.isFinite(Number(x))).map(Number),s=svg('svg',{viewBox:'0 0 100 30',class:'fd-spark'});if(values.length<2)return s;const mn=Math.min(...values),mx=Math.max(...values),span=mx-mn||1;s.append(svg('path',{d:values.map((x,i)=>(i?'L':'M')+(i/(values.length-1)*98+1)+' '+(27-(x-mn)/span*24)).join(' '),stroke:values.at(-1)>=values[0]?'#d66c65':'#5087c5',fill:'none','stroke-width':1.6}));return s;}
 function visibleRows(){let rows=(DATA?.rows||[]).filter(r=>r.sector!=='ETF·ETN');const q=search.value.trim().toLowerCase();if(q)rows=rows.filter(r=>(r.name+' '+r.code+' '+r.segment+' '+(r.market_theme||'')+' '+(r.themes||[]).map(x=>x.name).join(' ')+' '+(r.event_type||'')).toLowerCase().includes(q));if(groupFilter)rows=rows.filter(r=>groupFilter.has(r.code));const value=r=>sort.value==='burst'?r.burst_multiple:sort.value==='total'?r.turnover_krw:sort.value==='query'?(r.query_rank?-r.query_rank:null):r.interval_turnover_krw;return rows.sort((a,b)=>((value(a)==null)-(value(b)==null))||((value(b)||0)-(value(a)||0)));}
 function choose(code){selected=code;renderTable();renderDetail();}
 function renderTable(){tbody.replaceChildren();for(const r of visibleRows()){const tr=el('tr');tr.dataset.selected=String(r.code===selected);const namecell=el('td'),b=el('button',r.name,'fd-name');b.addEventListener('click',()=>choose(r.code));namecell.append(b,el('div',r.code+' · '+(r.market_theme?('테마 '+r.market_theme+' · '):'')+r.segment,'fd-small'));tr.append(namecell,el('td',rate(r.change_pct),sign(r.change_pct)));
 const total=el('td',money(r.turnover_krw));total.title=r.turnover_krw==null?'값 미확인':fmt(r.turnover_krw,0)+' 원';tr.append(total);
 const d=el('td',money(r.interval_turnover_krw));d.append(el('div',r.delta_state==='OK'?(fmt(r.interval_seconds,1)+'초 관측'):r.delta_state==='NO_BASELINE'?'첫 관측 · 비교 대기':'비교 불가 · '+r.delta_state,'fd-small'));tr.append(d,el('td',money(r.five_min_turnover_krw)));
 const burst=el('td',r.burst_multiple==null?'—':fmt(r.burst_multiple,1)+'배');if(r.burst_multiple>=3)burst.className='fd-up';burst.title='직전 5개 이상 구간의 초당 거래대금 중앙값 대비';tr.append(burst);
 const cap=el('td',money(r.cap_krw));cap.append(el('div',r.trade_to_cap_pct==null?'비율 미확인':fmt(r.trade_to_cap_pct,2)+'%','fd-small'));tr.append(cap);const c=el('td');c.append(spark(r.spark),button('차트',()=>openChart(r.code)));tr.append(c);tbody.append(tr);}
 if(!tbody.children.length){const tr=el('tr'),td=el('td','해당 표본이 없습니다. 관측 수집이 시작되면 표시됩니다.');td.colSpan=8;tr.append(td);tbody.append(tr);}}
 function renderRotation(){rotationBox.replaceChildren();const r=DATA?.theme_rotation||{};const head=el('div',null,'fd-rotation-head'),left=el('div');left.append(el('strong','최근 30초 구간별 시장테마 거래비중'),el('div','동일 종목 공통표본 '+(r.common_stocks||0)+'개 · 최대 최근 10구간','fd-sub'));head.append(left,badge('순매수 아님','fd-amber'));rotationBox.append(head);const list=(r.series||[]).slice(0,8);if(!list.length){rotationBox.append(el('div','공통표본 구간이 아직 부족합니다. 새 관측이 연속으로 쌓인 뒤 표시됩니다.','fd-empty'));return;}for(const x of list){const row=el('div',null,'fd-rotation-row');const name=el('strong',x.name),share=el('span',x.current_share_pct==null?'—':fmt(x.current_share_pct,1)+'%'),chg=el('span',x.change_pp==null?'—':(x.change_pp>=0?'▲ ':'▼ ')+fmt(Math.abs(x.change_pp),1)+'%p',x.change_pp>0?'fd-up':x.change_pp<0?'fd-down':'');const p=spark((x.share_pct||[]).map((v,i)=>({value:v,time:(r.times||[])[i]})));p.title='최근 구간 거래대금 비중';row.append(name,share,chg,p);rotationBox.append(row);}}
function renderGroups(){groupbox.replaceChildren();let groups=mode==='catalyst'?DATA?.catalyst_groups:mode==='theme'?DATA?.theme_groups:DATA?.sector_groups;for(const g of (groups||[]).slice(0,18)){const card=el('article',null,'fd-group'),head=el('div',null,'fd-ghead');head.append(el('h3',g.name),el('div',g.stock_count+'종목 · 비교 '+g.known_deltas+'종목 / 동일표본 '+g.common_stock_count+'종목','fd-sub'));const m=el('div',null,'fd-gmetrics'),a=el('div'),b=el('div');a.append(el('div','최근 구간 거래대금','fd-sub'),el('strong',money(g.interval_turnover_krw)));b.append(el('div','누적 거래대금','fd-sub'),el('strong',money(g.turnover_krw)));m.append(a,b);head.append(m);const track=el('div',null,'fd-share'),bar=el('span');bar.style.width=Math.max(0,Math.min(100,g.share_pct||0))+'%';track.append(bar);head.append(track);const sh=g.share_pct==null?'비중 비교 대기':fmt(g.share_pct,1)+'% · '+(g.share_change_pp==null?'이전 구간 대기':(g.share_change_pp>=0?'▲ ':'▼ ')+fmt(Math.abs(g.share_change_pp),1)+'%p');head.append(badge(sh,g.share_change_pp>0?'fd-teal':g.share_change_pp<0?'fd-purple':''));if(mode==='catalyst')head.append(el('div',g.event_type?'AI 재료 유형 · 동일 사건이라는 뜻은 아님':'분석된 재료 없음 · 시장테마만으로 이유를 만들지 않음','fd-sub'));if(mode==='theme')head.append(el('div','Kiwoom 테마그룹 소속 · 주가 원인으로 단정하지 않음','fd-sub'));card.append(head);
 for(const code of(g.stock_codes||[]).slice(0,4)){const r=rowOf(code);if(!r)continue;const peer=el('div',null,'fd-peer'),n=el('button',r.name);n.addEventListener('click',()=>choose(r.code));peer.append(n,el('span',rate(r.change_pct),sign(r.change_pct)),el('span',money(r.interval_turnover_krw)));card.append(peer);}const filter=button('이 군 '+g.stock_count+'종목 보기',()=>{groupFilter=new Set(g.stock_codes);renderTable();sheet.scrollIntoView({block:'start',behavior:'smooth'});});filter.style.margin='8px 12px';card.append(filter);groupbox.append(card);}
 if(!groupbox.children.length)groupbox.append(el('div','SOR 관측 자료를 모으는 중입니다. 과거 데이터를 새 구간으로 재해석하지 않습니다.','fd-empty'));}
 function renderDetail(){detail.replaceChildren();const r=rowOf(selected);if(!r){detail.append(el('h3','종목을 선택하세요'),el('p','최근 거래대금이 증가한 종목부터 확인하고, 재료의 새로움과 차트는 별도로 비교합니다.'));return;}
 detail.append(el('h3',r.name+' · '+r.code),el('div',r.segment,'fd-sub'));if(r.market_theme)detail.append(badge('시장테마 · '+r.market_theme,'fd-purple'));if((r.themes||[]).length>1)detail.append(el('div','테마 소속 · '+r.themes.map(x=>x.name).join(' · '),'fd-sub'));detail.append(badge(rate(r.change_pct)),el('div','최근 체결 '+stamp(r.exchange_at)+' / 수집 '+stamp(r.received_at),'fd-sub'));
 const controls=el('div',null,'fd-controls');controls.append(button('3분봉 · 일봉 차트',()=>openChart(r.code)),button('필터 해제',()=>{groupFilter=null;search.value='';renderTable();}));detail.append(controls);
 detail.append(el('p','누적 '+money(r.turnover_krw)+' / 최근 '+(r.interval_seconds==null?'구간':fmt(r.interval_seconds,1)+'초')+' '+money(r.interval_turnover_krw)+' / 5분 '+money(r.five_min_turnover_krw)));
 if((r.quality_flags||[]).length)detail.append(el('div','자료 점검: '+r.quality_flags.join(' · '),'fd-note'));
 if(r.research){detail.append(badge(r.research_stale?'과거 AI 보고서 · 재검토 필요':'인용 포함 AI 보고서',r.research_stale?'fd-amber':'fd-teal'),el('div','작성 '+stamp(r.research.completed_at)+' · '+(r.research.model||''),'fd-sub'));const sections=r.research.sections||{};let rendered=0;for(const name of['핵심 재료','새로움과 반복','시장 연결','반대 근거·미확인']){if(!sections[name])continue;detail.append(el('h4',name),annotation(sections[name]));rendered++;}if(!rendered)detail.append(annotation(r.research.report));const originals=el('details'),sum=el('summary','보고서 원문 · 출처');originals.append(sum,annotation(r.research.report));detail.append(originals);}
 else detail.append(el('h4','핵심 재료 · 분석 대기'),el('p','확인된 외부 AI 보고서가 아직 없습니다. 기사 제목이나 다른 종목의 사건을 상승 이유로 붙이지 않습니다.'),el('div','자동 조사: 거래 폭증·조회 상승·새 공개자료를 선별합니다. 기존 API 호출 한도 안에서 처리합니다.','fd-note'));
 const leads=el('details',null,'fd-links');leads.append(el('summary','공개자료 후보 '+(r.leads||[]).length+'건 · 종합 판단 전'));for(const l of r.leads||[]){const p=el('p');p.append(link(l.url,l.title||'원문'),el('div',(l.source||'')+' · '+(l.kind==='DART_LIST_ONLY'?'공시 목록 확인':'기사 제목 확인'),'fd-sub'));leads.append(p);}detail.append(leads,el('div','초기 세부업종 분류표(CURATED_V1)와 공식 업종을 구분합니다. 재료 분류는 AI가 작성한 후보이며 출처를 검토해야 합니다.','fd-sub'));}
 function render(d){DATA=d;if(!selected&&(d.rows||[]).length)selected=d.rows[0].code;state.textContent='수집 '+stamp(d.sample_time)+' · '+(d.rows||[]).length+'종목 · 최근 체결 '+d.recent_trade_count+'종목 · '+(d.recent_trade_count?'최근 관측 있음':'장외·체결 없음 또는 수집 대기');kpis.replaceChildren();const rs=(d.rows||[]).filter(r=>r.sector!=='ETF·ETN');const sum=(key)=>{const vs=rs.filter(r=>r[key]!=null);return vs.length?vs.reduce((a,r)=>a+r[key],0):null;};const data=[['표본 누적 거래대금',money(sum('turnover_krw')),'SOR / 원단위 변환'],['최근 구간 거래대금',money(sum('interval_turnover_krw')),'실제 관측 간격 사용'],['거래 속도 3배 이상',rs.filter(r=>r.burst_multiple>=3).length+'종목','직전 구간 중앙값 기준'],['재료 종합 보고서',rs.filter(r=>r.research).length+' / '+rs.length,'없으면 분석 대기']];for(const[k,v,n]of data){const c=el('div',null,'fd-kpi');c.append(el('div',k,'fd-sub'),el('strong',v),el('div',n,'fd-sub'));kpis.append(c);}renderRotation();groupnote.textContent='외부 AI '+(d.automation?.automatic?'자동 선별 켜짐':'자동 선별 꺼짐')+' · 오늘 '+(d.automation?.usage?.daily??0)+'/'+(d.automation?.daily_limit??'미확인')+'회(실패 포함) · 시장테마 매핑 '+(d.coverage?.theme_mapped_stocks||0)+'/'+(d.coverage?.observed_stocks||0)+'종목 · 공통 표본 '+(d.coverage?.common_stocks||0)+'종목의 직전·현재 구간 비중을 비교합니다. 시장테마는 Kiwoom 테마그룹 소속, 재료유형은 인용 포함 AI 보고서에서 분리합니다. 신규 편입·누락은 비중 이동에서 제외하며 전체 시장 순유입을 뜻하지 않습니다.';renderGroups();renderTable();renderDetail();}
 function drawChart(info,frame,container){container.replaceChildren();const input=frame==='daily'?info.daily:info.minute,rows=(input||[]).filter(r=>['open','high','low','close'].every(k=>Number.isFinite(r[k])&&r[k]>0)&&r.high>=Math.max(r.open,r.close,r.low)&&r.low<=Math.min(r.open,r.close));if(!rows.length){container.append(el('div','저장된 '+(frame==='daily'?'일봉':'3분봉')+'이 없습니다. 선택 종목을 차트 수집 대상에 넣었습니다. 다음 수집 주기 이후 다시 확인하세요.','fd-empty'));return;}
 const W=900,H=280,left=60,right=10,top=16,bottom=28,n=rows.length,spanX=W-left-right,bw=Math.max(1,spanX/n*.60);let lo=Math.min(...rows.map(r=>r.low)),hi=Math.max(...rows.map(r=>r.high));const span=hi-lo||hi*.01;lo-=span*.06;hi+=span*.06;const x=i=>left+(i+.5)*spanX/n,y=v=>top+(hi-v)/(hi-lo)*(H-top-bottom),s=svg('svg',{viewBox:'0 0 '+W+' '+H,role:'img','aria-label':frame==='daily'?'일봉 캔들':'3분봉 캔들'});
 for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;const yy=y(v);s.append(svg('line',{x1:left,y1:yy,x2:W-right,y2:yy,stroke:'#e6edf5'}));const t=svg('text',{x:left-6,y:yy+4,'font-size':10,'text-anchor':'end',fill:'#74849a'});t.textContent=fmt(v,0);s.append(t);}
 rows.forEach((r,i)=>{const c=r.close>=r.open?'#d15a61':'#4776bc',g=svg('g',{opacity:r.provisional?.5:1});g.append(svg('line',{x1:x(i),x2:x(i),y1:y(r.high),y2:y(r.low),stroke:c,'stroke-width':1}));g.append(svg('rect',{x:x(i)-bw/2,y:Math.min(y(r.open),y(r.close)),width:bw,height:Math.max(1,Math.abs(y(r.open)-y(r.close))),fill:r.close>=r.open?'#fff':c,stroke:c,'stroke-width':1}));const t=svg('title');t.textContent=r.time+'\n시 '+r.open+' 고 '+r.high+' 저 '+r.low+' 종 '+r.close+' / 거래량 '+r.volume+(r.provisional?' (미완성 가능)':'');g.append(t);s.append(g);});
 const ma=[];for(let i=19;i<rows.length;i++){const mean=rows.slice(i-19,i+1).reduce((a,r)=>a+r.close,0)/20;ma.push((ma.length?'L':'M')+x(i)+' '+y(mean));}if(ma.length)s.append(svg('path',{d:ma.join(' '),fill:'none',stroke:'#d79625','stroke-width':1.8}));
 if(frame==='daily'&&rows.length>20){const prior=rows.slice(0,-1).filter(r=>!r.provisional).slice(-60),ph=Math.max(...prior.map(r=>r.high));if(ph>=lo&&ph<=hi)s.append(svg('line',{x1:left,x2:W-right,y1:y(ph),y2:y(ph),stroke:'#7a5dbe','stroke-dasharray':'4 4'}));}
 const first=svg('text',{x:left,y:H-6,'font-size':10,fill:'#74849a'});first.textContent=frame==='daily'?rows[0].time:stamp(rows[0].time)+' KST';const last=svg('text',{x:W-right,y:H-6,'font-size':10,fill:'#74849a','text-anchor':'end'});last.textContent=frame==='daily'?rows.at(-1).time:stamp(rows.at(-1).time)+' KST';s.append(first,last);container.append(s);
 const vs=svg('svg',{viewBox:'0 0 '+W+' 72',role:'img','aria-label':'거래량'}),vm=Math.max(1,...rows.map(r=>r.volume||0));rows.forEach((r,i)=>{const height=Math.max(0,(r.volume||0)/vm*58);vs.append(svg('rect',{x:x(i)-bw/2,y:62-height,width:bw,height,fill:r.close>=r.open?'#e8acb0':'#a5bedf'}));});container.append(vs,el('div','빨강/파랑: 캔들 · 주황: 20봉 평균 · 보라 점선(일봉): 직전 최대 60일 고가 · 아래: 거래량','fd-sub'),el('div','마지막 봉 '+stamp(frame==='daily'?rows.at(-1).time+'T00:00:00+09:00':rows.at(-1).time)+' / 반투명 봉은 미완성 가능','fd-sub'));}
 async function openChart(code){focusCode=code;const version=++chartVersion;dialog.replaceChildren();const r=rowOf(code),head=el('div',null,'fd-head'),title=el('h3',(r?.name||code)+' · 종목 차트'),close=button('닫기',()=>dialog.close());head.append(title,close);const controls=el('div',null,'fd-controls'),chart=el('div','차트 자료 확인 중','fd-chartbox'),meta=el('div',null,'fd-sub');const b1=button('KRX 3분봉',()=>{chartFrame='minute';if(chartInfo)drawChart(chartInfo,chartFrame,chart);}),b2=button('KRX 일봉',()=>{chartFrame='daily';if(chartInfo)drawChart(chartInfo,chartFrame,chart);}),reload=button('저장 차트 새로고침',()=>openChart(code));controls.append(b1,b2,reload);dialog.append(head,controls,meta,chart);if(!dialog.open)dialog.showModal();
 try{chartInfo=await get('/api/flow-chart/'+encodeURIComponent(code));if(version!==chartVersion)return;meta.textContent=chartInfo.price_source;drawChart(chartInfo,chartFrame,chart);if(chartInfo.mimosa){dialog.append(el('div','기존 미모사 관측: '+chartInfo.mimosa.state_ko+' · '+chartInfo.mimosa.minute_trend+' / '+stamp(chartInfo.mimosa.snapshot_time)+' · 검증 전 규칙 판독','fd-note'));}get('/api/flow-chart-request/'+encodeURIComponent(code),{method:'POST'}).catch(()=>{});}catch(e){chart.textContent='차트 조회 실패 '+e.message;}close.focus();}
 async function load(force=false){if(busy||(!force&&(!view.classList.contains('active')||document.hidden||Date.now()-lastLoaded<28000)))return;if(!accessKey()){state.textContent='대시보드 접속키 필요';return;}busy=true;try{const d=await get('/api/flow-desk');lastLoaded=Date.now();render(d);}catch(e){state.textContent='흐름 자료 응답 대기 · '+e.message+' · 기존 화면 유지';}finally{busy=false;}}
 byEvent.addEventListener('click',()=>{mode='catalyst';groupFilter=null;byEvent.setAttribute('aria-pressed','true');byTheme.setAttribute('aria-pressed','false');bySector.setAttribute('aria-pressed','false');renderGroups();renderTable();});byTheme.addEventListener('click',()=>{mode='theme';groupFilter=null;byEvent.setAttribute('aria-pressed','false');byTheme.setAttribute('aria-pressed','true');bySector.setAttribute('aria-pressed','false');renderGroups();renderTable();});bySector.addEventListener('click',()=>{mode='sector';groupFilter=null;byEvent.setAttribute('aria-pressed','false');byTheme.setAttribute('aria-pressed','false');bySector.setAttribute('aria-pressed','true');renderGroups();renderTable();});search.addEventListener('input',()=>{groupFilter=null;renderTable();});sort.addEventListener('change',renderTable);refresh.addEventListener('click',()=>load(true));
 // Add chart buttons to existing ranking tables without altering their renderers.
 let attaching=false;const observer=new MutationObserver(()=>{if(attaching)return;attaching=true;requestAnimationFrame(()=>{for(const id of ['queryRows','tradeRows'])for(const row of document.querySelectorAll('#'+id+' tr')){const code=[...row.querySelectorAll('.sub')].map(n=>n.textContent.trim()).find(t=>/^[0-9A-Z]{6}$/.test(t));const cell=row.cells[row.cells.length-1];if(code&&cell&&!cell.querySelector('.fd-chart-shortcut')){const b=button('차트 열기',()=>openChart(code));b.classList.add('fd-chart-shortcut');cell.append(el('div'),b);}}attaching=false;});});for(const id of ['queryRows','tradeRows']){const n=document.getElementById(id);if(n)observer.observe(n,{childList:true,subtree:true});}
 setInterval(()=>load(false),30000);load(true);
})();
